"""Seed MongoDB with backend interview questions for the EthioCode practice page."""
import asyncio
from datetime import datetime

from app.config import settings
from app.database import db


def question(
    slug,
    title,
    category,
    subcategory,
    difficulty,
    question_type,
    question_text,
    answer_text,
    tags,
    points,
    minutes,
    language=None,
    companies=None,
):
    now = datetime.utcnow()
    return {
        "slug": slug,
        "title": title,
        "category": category,
        "subcategory": subcategory,
        "difficulty": difficulty,
        "question_type": question_type,
        "question_text": question_text,
        "question_text_am": "",
        "answer_text": answer_text,
        "answer_text_am": "",
        "sample_solution": "",
        "sample_solution_code": "",
        "initial_code": "",
        "language": language or category,
        "test_cases": [],
        "hints": [],
        "time_limit_seconds": minutes * 60,
        "points": points,
        "tags": tags,
        "companies_asked": companies or ["Chapa", "Dashen Bank", "Safaricom Ethiopia"],
        "total_attempts": 0,
        "correct_attempts": 0,
        "success_rate": 0.0,
        "created_at": now,
        "updated_at": now,
    }


BACKEND_QUESTIONS = [
    question(
        "python-async-await-api",
        "Explain Python async and await",
        "python",
        "async",
        "intermediate",
        "theoretical",
        "Explain how async and await work in Python and when you would use them in a backend API.",
        "async and await let Python suspend I/O-bound coroutines while the event loop continues other work. They are useful for database calls, HTTP calls, queues, and websocket handlers, but not for CPU-heavy work unless it is moved to workers.",
        ["python", "async", "fastapi"],
        20,
        10,
        "python",
    ),
    question(
        "python-fastapi-dependency-injection",
        "FastAPI dependency injection",
        "python",
        "fastapi",
        "beginner",
        "theoretical",
        "How does FastAPI dependency injection help structure authentication, database sessions, and shared services?",
        "Dependencies let route handlers declare reusable requirements. FastAPI resolves them per request, which keeps auth, validation, database access, and service setup outside the route body.",
        ["python", "fastapi", "api"],
        15,
        8,
        "python",
    ),
    question(
        "python-background-jobs",
        "Background jobs in Python APIs",
        "python",
        "queues",
        "advanced",
        "system_design",
        "A payment webhook arrives and you must send email, update analytics, and call another API. What should happen synchronously and what should become a background job?",
        "Acknowledge the webhook after validating and safely storing the event. Slow or retryable side effects should go to a queue or background worker with idempotency keys and retry policies.",
        ["python", "queues", "webhooks"],
        30,
        15,
        "python",
        ["Chapa", "SantimPay"],
    ),
    question(
        "java-thread-pools-api",
        "Java thread pools for APIs",
        "java",
        "concurrency",
        "beginner",
        "theoretical",
        "What is a thread pool in Java, and why is it useful for backend request handling?",
        "A thread pool reuses worker threads, reducing thread creation overhead and controlling concurrency. It helps keep backend services stable under load.",
        ["java", "threads", "api"],
        15,
        8,
        "java",
    ),
    question(
        "java-spring-transaction-boundaries",
        "Spring transaction boundaries",
        "java",
        "spring",
        "intermediate",
        "debugging",
        "A Spring service saves an order, charges a wallet, and sends a notification. Where should the transaction boundary be and why?",
        "Database changes that must be atomic should be inside the transaction. External side effects like notifications should run after commit or through an outbox pattern.",
        ["java", "spring", "transactions"],
        25,
        12,
        "java",
    ),
    question(
        "java-memory-leak-diagnosis",
        "Diagnose a Java memory leak",
        "java",
        "jvm",
        "advanced",
        "debugging",
        "A Java API gradually consumes more memory until it crashes. What tools and steps would you use to diagnose the issue?",
        "Check metrics, heap dumps, GC logs, allocation profiles, and object retention paths. Look for unbounded caches, static collections, listener leaks, and large request buffers.",
        ["java", "jvm", "debugging"],
        30,
        15,
        "java",
    ),
    question(
        "node-event-loop-under-load",
        "Node.js event loop under load",
        "nodejs",
        "runtime",
        "intermediate",
        "theoretical",
        "Describe how the Node.js event loop handles concurrent requests and what can block it.",
        "Node.js uses an event loop to schedule callbacks for async work. CPU-heavy synchronous code, blocking file operations, and large JSON parsing can block the loop.",
        ["nodejs", "event-loop", "performance"],
        20,
        10,
        "javascript",
    ),
    question(
        "node-express-error-handling",
        "Express error handling",
        "nodejs",
        "express",
        "beginner",
        "debugging",
        "How do you handle async errors in Express routes without crashing the server?",
        "Wrap async route handlers, pass errors to next, and use centralized error middleware. Avoid unhandled promise rejections and avoid leaking stack traces to users.",
        ["nodejs", "express", "errors"],
        15,
        8,
        "javascript",
    ),
    question(
        "node-queue-worker-design",
        "Design a Node.js queue worker",
        "nodejs",
        "queues",
        "advanced",
        "system_design",
        "Design a Node.js worker that processes SMS notifications reliably for a fintech product.",
        "Use a durable queue, idempotency keys, retry with backoff, dead-letter queues, provider timeouts, rate limits, and metrics for success/failure rates.",
        ["nodejs", "queues", "reliability"],
        30,
        15,
        "javascript",
        ["Chapa", "Ethio Telecom"],
    ),
    question(
        "mongodb-indexes-job-platform",
        "Design indexes for a job platform",
        "databases",
        "indexing",
        "advanced",
        "system_design",
        "A jobs page filters by location, skill, salary, and posted date. Which indexes would you create and why?",
        "Start with the most common query patterns. Use compound indexes that match equality filters first, then range/sort fields. Validate with explain plans and avoid over-indexing.",
        ["mongodb", "indexes", "query-planning"],
        30,
        15,
        "mongodb",
    ),
    question(
        "sql-transactions-isolation",
        "SQL transaction isolation",
        "databases",
        "transactions",
        "intermediate",
        "theoretical",
        "Explain dirty reads, non-repeatable reads, and phantom reads. How do isolation levels affect them?",
        "Isolation levels define what concurrent transactions can observe. Higher isolation reduces anomalies but can increase locking, latency, or serialization failures.",
        ["sql", "transactions", "isolation"],
        25,
        12,
        "sql",
    ),
    question(
        "database-pagination-scale",
        "Pagination at scale",
        "databases",
        "pagination",
        "beginner",
        "theoretical",
        "Why can offset pagination become slow, and when would you use cursor pagination instead?",
        "Large offsets force the database to scan and discard rows. Cursor pagination uses a stable ordered key and is better for large feeds or infinite scroll.",
        ["databases", "pagination", "performance"],
        15,
        8,
        "sql",
    ),
    question(
        "system-design-code-runner",
        "Design a scalable code runner",
        "system_design",
        "architecture",
        "expert",
        "system_design",
        "Design a secure service that executes user-submitted code for interview practice.",
        "Use isolated workers or containers, strict CPU/memory/time limits, network restrictions, queues, result storage, sandbox cleanup, and auditing.",
        ["system-design", "containers", "security"],
        40,
        20,
    ),
    question(
        "system-design-food-delivery",
        "Design a food delivery backend",
        "system_design",
        "distributed-systems",
        "advanced",
        "system_design",
        "Design the backend for an Addis Ababa food delivery app with restaurants, drivers, payments, and live order tracking.",
        "Separate order, payment, restaurant, dispatch, and tracking services. Use events for status changes, geospatial indexes for driver matching, and idempotent payment flows.",
        ["system-design", "payments", "geo"],
        35,
        18,
        companies=["Chapa", "Ride", "Deliver Addis"],
    ),
    question(
        "system-design-notification-service",
        "Design a notification service",
        "system_design",
        "messaging",
        "intermediate",
        "system_design",
        "Design a service that sends email, SMS, and push notifications for course updates and job alerts.",
        "Use templates, user preferences, queues, provider adapters, retry policies, rate limits, and delivery status tracking.",
        ["system-design", "notifications", "queues"],
        25,
        12,
    ),
    question(
        "devops-docker-health-checks",
        "Docker health checks",
        "devops",
        "containers",
        "beginner",
        "theoretical",
        "How would you add a health check for a backend service running in Docker?",
        "Expose a lightweight health endpoint and configure Docker or the orchestrator to probe it. The check should verify critical dependencies without being too expensive.",
        ["docker", "health-checks", "deployment"],
        15,
        8,
    ),
    question(
        "devops-ci-cd-fastapi",
        "CI/CD for a FastAPI service",
        "devops",
        "ci-cd",
        "intermediate",
        "system_design",
        "What stages should a CI/CD pipeline include for a FastAPI backend deployed with Docker?",
        "Run linting, tests, security checks, build an image, scan it, push to registry, deploy by environment, run migrations, and verify health.",
        ["ci-cd", "fastapi", "docker"],
        25,
        12,
    ),
    question(
        "devops-rollback-strategy",
        "Backend rollback strategy",
        "devops",
        "deployment",
        "advanced",
        "system_design",
        "A new backend release breaks payment callbacks. How do you roll back safely?",
        "Use health checks, canary or blue-green deployments, database-compatible changes, feature flags, quick image rollback, and replayable idempotent webhook handling.",
        ["deployment", "rollback", "reliability"],
        30,
        15,
    ),
    question(
        "cloud-secure-file-uploads",
        "Choose cloud storage for uploads",
        "cloud",
        "storage",
        "intermediate",
        "theoretical",
        "A backend API accepts user file uploads. How would you store those files in the cloud and keep access secure?",
        "Store files in private object storage, validate file type and size, scan files when needed, and serve them through signed URLs or scoped permissions.",
        ["cloud", "object-storage", "security"],
        25,
        12,
    ),
    question(
        "cloud-auto-scaling-api",
        "Auto-scale a backend API",
        "cloud",
        "scaling",
        "advanced",
        "system_design",
        "How would you auto-scale a backend API during a national exam registration traffic spike?",
        "Use stateless API instances, load balancing, horizontal scaling by CPU/RPS/queue depth, database connection pooling, caching, and capacity testing before launch.",
        ["cloud", "autoscaling", "traffic"],
        35,
        18,
    ),
    question(
        "cloud-secrets-management",
        "Cloud secrets management",
        "cloud",
        "security",
        "beginner",
        "theoretical",
        "Where should API keys and database passwords live in a cloud deployment?",
        "Use a secret manager or encrypted environment injection, never commit secrets, rotate credentials, scope permissions, and audit access.",
        ["cloud", "secrets", "security"],
        15,
        8,
    ),
]


def build_extra_questions():
    specs = {
        "python": [
            ("python-gil-api-performance", "Python GIL and API performance", "runtime", "advanced", "theoretical", "What is the GIL, and how does it affect CPU-bound backend workloads?", "The GIL allows only one thread to execute Python bytecode at a time. Use multiprocessing, native extensions, task queues, or separate services for CPU-heavy work.", ["python", "gil", "performance"], 30, 15, "python"),
            ("python-pydantic-validation", "Pydantic validation in APIs", "validation", "beginner", "theoretical", "Why should backend APIs validate request bodies with Pydantic models?", "Validation creates a clear contract, rejects bad input early, gives useful errors, and keeps route logic cleaner.", ["python", "pydantic", "validation"], 15, 8, "python"),
            ("python-sqlalchemy-session-scope", "SQLAlchemy session scope", "databases", "intermediate", "debugging", "Where should a SQLAlchemy session be opened and closed in a FastAPI app?", "Use a per-request dependency that opens the session, yields it to handlers, commits or rolls back intentionally, and closes it after the request.", ["python", "sqlalchemy", "sessions"], 25, 12, "python"),
            ("python-celery-vs-backgroundtasks", "Celery vs FastAPI BackgroundTasks", "queues", "intermediate", "theoretical", "When would you choose Celery or RQ instead of FastAPI BackgroundTasks?", "Use a real queue for durable, retryable, long-running, or distributed work. BackgroundTasks are best for small post-response tasks in the same process.", ["python", "celery", "queues"], 25, 12, "python"),
            ("python-idempotent-webhooks", "Idempotent webhook handlers", "payments", "advanced", "system_design", "How do you make a Python payment webhook handler idempotent?", "Store provider event IDs, check before processing, use atomic updates, keep payment state transitions explicit, and return success for duplicate delivered events.", ["python", "webhooks", "payments"], 30, 15, "python"),
            ("python-testing-fastapi", "Testing FastAPI routes", "testing", "beginner", "theoretical", "How would you test a FastAPI endpoint that depends on authentication and a database?", "Use TestClient or httpx, override dependencies for auth and database sessions, seed known data, and assert response codes and side effects.", ["python", "fastapi", "testing"], 15, 8, "python"),
            ("python-cache-aside-redis", "Cache-aside with Redis", "caching", "intermediate", "system_design", "Explain the cache-aside pattern for a Python backend using Redis.", "The app checks Redis first, falls back to the database on a miss, stores the result with a TTL, and invalidates or refreshes on writes.", ["python", "redis", "caching"], 25, 12, "python"),
        ],
        "java": [
            ("java-rest-controller-validation", "Spring request validation", "spring", "beginner", "theoretical", "How do you validate request payloads in a Spring Boot REST controller?", "Use DTOs with validation annotations, @Valid, global exception handlers, and avoid exposing persistence entities directly.", ["java", "spring", "validation"], 15, 8, "java"),
            ("java-executorservice-backpressure", "ExecutorService backpressure", "concurrency", "advanced", "system_design", "How do you prevent a Java ExecutorService from accepting unlimited work?", "Use bounded queues, rejection policies, timeouts, rate limits, and metrics so overload is controlled instead of becoming memory pressure.", ["java", "concurrency", "backpressure"], 30, 15, "java"),
            ("java-jpa-n-plus-one", "JPA N+1 query problem", "jpa", "intermediate", "debugging", "What is the N+1 query problem in JPA, and how do you fix it?", "It occurs when fetching a list triggers one extra query per row. Use fetch joins, entity graphs, projections, batching, and query logging.", ["java", "jpa", "databases"], 25, 12, "java"),
            ("java-exception-handling-api", "Java API exception handling", "api", "beginner", "theoretical", "How should a Java backend map exceptions to HTTP responses?", "Use centralized exception handling, stable error shapes, correct status codes, safe messages for clients, and detailed logs for operators.", ["java", "errors", "api"], 15, 8, "java"),
            ("java-records-dtos", "Java records for DTOs", "language", "intermediate", "theoretical", "When are Java records useful in backend applications?", "Records are concise immutable data carriers, useful for DTOs, responses, events, and value objects where identity and mutation are not needed.", ["java", "records", "dto"], 20, 10, "java"),
            ("java-microservice-timeouts", "Timeouts in Java microservices", "resilience", "advanced", "system_design", "How do you set timeouts and retries for Java service-to-service calls?", "Use connect/read timeouts, retry only safe operations, add jittered backoff, circuit breakers, idempotency, and observability.", ["java", "resilience", "microservices"], 30, 15, "java"),
            ("java-security-jwt", "JWT authentication in Spring", "security", "intermediate", "theoretical", "What should a Spring backend verify before trusting a JWT?", "Verify signature, issuer, audience, expiry, token type, required claims, and map scopes or roles carefully.", ["java", "jwt", "security"], 25, 12, "java"),
        ],
        "nodejs": [
            ("node-promise-error-handling", "Promise error handling", "runtime", "beginner", "debugging", "What happens when a promise rejection is not handled in a Node.js backend?", "Unhandled rejections can crash or destabilize the process depending on configuration. Always await, catch, or pass errors to centralized handlers.", ["nodejs", "promises", "errors"], 15, 8, "javascript"),
            ("node-streaming-large-files", "Streaming large files", "streams", "intermediate", "theoretical", "Why should a Node.js API stream large files instead of reading them fully into memory?", "Streams process data in chunks, reducing memory use and allowing backpressure between producers and consumers.", ["nodejs", "streams", "files"], 25, 12, "javascript"),
            ("node-clustering-workers", "Node.js clustering", "scaling", "advanced", "system_design", "How can a Node.js backend use multiple CPU cores?", "Run multiple worker processes with clustering, PM2, containers, or an orchestrator. Keep workers stateless and share state through external stores.", ["nodejs", "scaling", "cluster"], 30, 15, "javascript"),
            ("node-middleware-order", "Express middleware order", "express", "beginner", "debugging", "Why does middleware order matter in Express?", "Express runs middleware in registration order. Auth, parsing, routing, and error middleware must be placed deliberately.", ["nodejs", "express", "middleware"], 15, 8, "javascript"),
            ("node-rate-limiting-api", "Rate limiting a Node.js API", "security", "intermediate", "system_design", "Design rate limiting for a Node.js public API.", "Use Redis-backed counters or token buckets, key by user/IP/API key, return 429, and tune limits per endpoint risk.", ["nodejs", "redis", "rate-limit"], 25, 12, "javascript"),
            ("node-orm-transactions", "Transactions with a Node ORM", "databases", "intermediate", "theoretical", "How do you use database transactions safely from a Node.js service?", "Keep transaction scope short, pass the transaction object through all queries, handle rollback on errors, and avoid slow external calls inside transactions.", ["nodejs", "transactions", "orm"], 25, 12, "javascript"),
            ("node-memory-leak", "Find a Node.js memory leak", "debugging", "advanced", "debugging", "A Node service memory graph rises until restart. How do you investigate?", "Use heap snapshots, allocation profiling, metrics, load tests, and inspect global caches, listeners, timers, and retained request objects.", ["nodejs", "memory", "debugging"], 30, 15, "javascript"),
        ],
        "databases": [
            ("database-normalization-tradeoffs", "Normalization tradeoffs", "schema-design", "beginner", "theoretical", "What is normalization, and when might denormalization be useful?", "Normalization reduces duplication and update anomalies. Denormalization can improve read performance when consistency and write complexity are managed.", ["databases", "schema", "normalization"], 15, 8, "sql"),
            ("database-optimistic-locking", "Optimistic locking", "transactions", "intermediate", "theoretical", "How does optimistic locking prevent lost updates?", "Rows include a version or timestamp. Updates check the expected version and fail if another transaction changed it first.", ["databases", "locking", "transactions"], 25, 12, "sql"),
            ("database-read-replicas", "Read replicas", "scaling", "intermediate", "system_design", "How do read replicas help a backend, and what consistency issue do they introduce?", "Read replicas scale reads and improve locality, but replication lag means users may not immediately see recent writes.", ["databases", "replication", "scaling"], 25, 12, "sql"),
            ("database-sharding-tenant", "Shard by tenant", "scaling", "advanced", "system_design", "When would you shard a database by tenant or customer ID?", "Shard when one database cannot meet storage or throughput needs. Tenant-based sharding can isolate load but complicates cross-tenant queries.", ["databases", "sharding", "multi-tenant"], 30, 15, "sql"),
            ("database-mongodb-aggregation", "MongoDB aggregation pipeline", "mongodb", "intermediate", "theoretical", "When would you use a MongoDB aggregation pipeline instead of application-side processing?", "Use aggregation to filter, group, join, transform, and summarize data near storage, reducing network transfer and app memory use.", ["mongodb", "aggregation", "analytics"], 25, 12, "mongodb"),
            ("database-connection-pooling", "Connection pooling", "performance", "beginner", "theoretical", "Why do backend apps use database connection pools?", "Pools reuse established connections, reduce connection overhead, and cap database concurrency to protect both app and database.", ["databases", "pooling", "performance"], 15, 8, "sql"),
            ("database-backups-restore", "Backup and restore strategy", "operations", "advanced", "system_design", "What should a production database backup strategy include?", "Use automated backups, point-in-time recovery, restore drills, retention policies, encryption, monitoring, and clear RPO/RTO targets.", ["databases", "backups", "recovery"], 30, 15, "sql"),
        ],
        "system_design": [
            ("system-design-url-shortener", "Design a URL shortener", "architecture", "beginner", "system_design", "Design a backend for shortening URLs and redirecting users quickly.", "Use unique short codes, a mapping store, cache hot redirects, track analytics asynchronously, and protect against abuse.", ["system-design", "cache", "api"], 20, 10, None),
            ("system-design-chat-app", "Design a chat backend", "realtime", "advanced", "system_design", "Design a real-time chat backend for students and mentors.", "Use websocket gateways, message persistence, delivery receipts, fanout, presence, rate limits, and offline notification workers.", ["system-design", "websocket", "chat"], 35, 18, None),
            ("system-design-payment-ledger", "Design a payment ledger", "fintech", "expert", "system_design", "Design a payment ledger for wallet balances and transfers.", "Use append-only ledger entries, double-entry accounting, idempotency, reconciliation, immutable audit logs, and strict transaction boundaries.", ["system-design", "payments", "ledger"], 40, 20, None),
            ("system-design-video-processing", "Design video processing", "media", "advanced", "system_design", "Design a service that processes uploaded course videos.", "Upload to object storage, enqueue processing jobs, transcode workers, store status, generate thumbnails, and serve via CDN.", ["system-design", "queues", "video"], 35, 18, None),
            ("system-design-search-service", "Design search for jobs", "search", "intermediate", "system_design", "Design search for jobs by title, skills, location, and company.", "Use a search index, background syncing, filters/facets, ranking rules, typo handling, and fallbacks when indexing lags.", ["system-design", "search", "jobs"], 25, 12, None),
            ("system-design-analytics-dashboard", "Design analytics dashboard", "analytics", "intermediate", "system_design", "Design backend analytics for course progress and interview practice.", "Capture events, stream or batch process them, aggregate by user/category/time, and serve precomputed metrics to dashboards.", ["system-design", "analytics", "events"], 25, 12, None),
            ("system-design-multi-tenant-saas", "Design multi-tenant SaaS", "saas", "advanced", "system_design", "Design a backend that supports many companies on one platform.", "Model tenants explicitly, enforce tenant isolation in queries, manage roles, choose shared vs isolated databases, and audit access.", ["system-design", "saas", "multi-tenant"], 35, 18, None),
        ],
        "devops": [
            ("devops-kubernetes-readiness", "Kubernetes readiness vs liveness", "kubernetes", "intermediate", "theoretical", "What is the difference between readiness and liveness probes?", "Readiness controls whether traffic is sent to a pod. Liveness decides whether the pod should be restarted.", ["kubernetes", "health-checks", "devops"], 25, 12, None),
            ("devops-env-config", "Environment config management", "configuration", "beginner", "theoretical", "How should staging and production backend configuration differ?", "Use environment-specific variables and secrets, not code branches. Keep defaults safe and validate required config at startup.", ["devops", "config", "environments"], 15, 8, None),
            ("devops-logs-metrics-traces", "Logs, metrics, and traces", "observability", "intermediate", "theoretical", "What is the difference between logs, metrics, and traces?", "Logs explain discrete events, metrics show numeric trends, and traces follow a request across services.", ["observability", "logs", "metrics"], 25, 12, None),
            ("devops-zero-downtime-migrations", "Zero-downtime migrations", "database", "advanced", "system_design", "How do you deploy a database schema change without downtime?", "Use backward-compatible migrations, expand-and-contract changes, dual writes when needed, and deploy app versions in the right order.", ["devops", "migrations", "deployment"], 30, 15, None),
            ("devops-container-image-size", "Reduce Docker image size", "containers", "beginner", "theoretical", "How can you reduce Docker image size for a backend service?", "Use slim base images, multi-stage builds, .dockerignore, remove build tools from runtime, and avoid copying unnecessary files.", ["docker", "images", "optimization"], 15, 8, None),
            ("devops-incident-response", "Backend incident response", "operations", "advanced", "theoretical", "A production API has high error rates. What are your first response steps?", "Triage scope, check dashboards/logs, roll back if needed, communicate status, mitigate customer impact, and record a post-incident review.", ["devops", "incident", "reliability"], 30, 15, None),
            ("devops-feature-flags", "Feature flags", "deployment", "intermediate", "theoretical", "Why are feature flags useful in backend deployments?", "They decouple release from activation, allow gradual rollout, fast disablement, A/B tests, and safer migrations.", ["devops", "feature-flags", "release"], 25, 12, None),
        ],
        "cloud": [
            ("cloud-load-balancer", "Cloud load balancers", "networking", "beginner", "theoretical", "What does a load balancer do for backend services?", "It distributes traffic across healthy instances, improves availability, terminates TLS when configured, and supports scaling.", ["cloud", "load-balancer", "availability"], 15, 8, None),
            ("cloud-cdn-api-assets", "CDN for backend assets", "cdn", "intermediate", "theoretical", "When should a backend use a CDN?", "Use a CDN for static assets, downloads, images, videos, and cacheable responses to reduce latency and backend load.", ["cloud", "cdn", "performance"], 25, 12, None),
            ("cloud-vpc-basics", "VPC basics", "networking", "beginner", "theoretical", "Why put databases in private subnets?", "Private subnets reduce exposure by preventing direct internet access. App services access databases through controlled network rules.", ["cloud", "vpc", "security"], 15, 8, None),
            ("cloud-managed-database-choice", "Choose managed database", "databases", "intermediate", "system_design", "When would you choose a managed cloud database over running your own?", "Managed databases reduce operational work for backups, patching, failover, monitoring, and scaling, though they can cost more and create provider coupling.", ["cloud", "database", "managed"], 25, 12, None),
            ("cloud-queue-service", "Cloud queue services", "messaging", "intermediate", "theoretical", "Why use a cloud queue between API and workers?", "Queues buffer spikes, decouple services, enable retries, improve reliability, and let workers scale independently.", ["cloud", "queues", "workers"], 25, 12, None),
            ("cloud-disaster-recovery", "Disaster recovery plan", "reliability", "advanced", "system_design", "What should a cloud disaster recovery plan include?", "Define RPO/RTO, backups, multi-zone or multi-region strategy, restore runbooks, failover testing, and monitoring.", ["cloud", "disaster-recovery", "reliability"], 30, 15, None),
            ("cloud-cost-control", "Control cloud cost", "cost", "advanced", "theoretical", "How do you prevent cloud costs from unexpectedly growing?", "Use budgets, alerts, tagging, autoscaling limits, right-sizing, storage lifecycle rules, and regular cost reviews.", ["cloud", "cost", "operations"], 30, 15, None),
        ],
    }

    items = []
    for category, entries in specs.items():
        for slug, title, subcategory, difficulty, question_type, prompt, answer, tags, points, minutes, language in entries:
            items.append(
                question(
                    slug,
                    title,
                    category,
                    subcategory,
                    difficulty,
                    question_type,
                    prompt,
                    answer,
                    tags,
                    points,
                    minutes,
                    language,
                )
            )
    return items


BACKEND_QUESTIONS.extend(build_extra_questions())


async def seed_backend_questions():
    await db.connect()
    collection = db.backend_questions
    await collection.create_index("slug", unique=True)
    await collection.create_index([("category", 1), ("difficulty", 1)])
    async for index in collection.list_indexes():
        if any(value == "text" for value in index.get("key", {}).values()):
            await collection.drop_index(index["name"])
    await collection.create_index(
        [("title", "text"), ("question_text", "text"), ("tags", "text")],
        default_language="none",
        language_override="search_language",
    )

    upserts = 0
    for item in BACKEND_QUESTIONS:
        update_fields = {key: value for key, value in item.items() if key != "created_at"}
        result = await collection.update_one(
            {"slug": item["slug"]},
            {"$set": update_fields, "$setOnInsert": {"created_at": item["created_at"]}},
            upsert=True,
        )
        if result.upserted_id or result.modified_count:
            upserts += 1

    total = await collection.count_documents({})
    await db.disconnect()
    print(f"Seeded/updated {upserts} backend questions. Total backend questions: {total}")


if __name__ == "__main__":
    asyncio.run(seed_backend_questions())
