// Widget registry — 50+ widgets across 8 role personas

export const ROLES = [
  { key: "developer",    icon: "👨‍💻", label: "Developer",    desc: "Learn, practice, build portfolio" },
  { key: "professional", icon: "💼",  label: "Professional", desc: "Upskill, network, find opportunities" },
  { key: "creator",      icon: "🎨",  label: "Creator",      desc: "Share knowledge, monetize" },
  { key: "freelancer",   icon: "🚀",  label: "Freelancer",   desc: "Find clients, manage projects" },
  { key: "founder",      icon: "🏢",  label: "Founder",      desc: "Build product, hire talent" },
  { key: "enterprise",   icon: "🏛️",  label: "Enterprise",   desc: "Collaborate, train employees" },
  { key: "instructor",   icon: "👨‍🏫", label: "Instructor",   desc: "Teach students, track progress" },
  { key: "recruiter",    icon: "🎯",  label: "Recruiter",    desc: "Find candidates, manage hiring" },
  { key: "admin",        icon: "⚙️",  label: "Admin",        desc: "Platform governance" },
];

export const SECTION_META = {
  learning:    { icon: "📚", label: "Learning Progress" },
  projects:    { icon: "📝", label: "Projects" },
  activity:    { icon: "⚡", label: "Recent Activity" },
  achievements:{ icon: "🏆", label: "Achievements" },
  jobs:        { icon: "💼", label: "Job Applications" },
  saved:       { icon: "🔖", label: "Saved Items" },
  skills:      { icon: "🎯", label: "Skill Analytics" },
  content:     { icon: "📝", label: "Content" },
  revenue:     { icon: "💰", label: "Revenue" },
  clients:     { icon: "👥", label: "Clients" },
  roadmap:     { icon: "🗺️", label: "Product Roadmap" },
  team:        { icon: "👥", label: "Team" },
  training:    { icon: "📚", label: "Training" },
  compliance:  { icon: "✅", label: "Compliance" },
  students:    { icon: "👨‍🎓", label: "Students" },
  courses:     { icon: "📖", label: "Courses" },
  gradebook:   { icon: "📋", label: "Gradebook" },
  pipeline:    { icon: "🔄", label: "Hiring Pipeline" },
  candidates:  { icon: "👤", label: "Candidates" },
  assessments: { icon: "📊", label: "Assessments" },
  users:       { icon: "👥", label: "User Management" },
  moderation:  { icon: "🛡️", label: "Moderation" },
  analytics:   { icon: "📈", label: "Analytics" },
  leaderboard: { icon: "🏅", label: "Leaderboard" },
  calendar:    { icon: "📅", label: "Calendar" },
  notifications:{ icon: "🔔", label: "Notifications" },
  weather:     { icon: "🌤️", label: "Weather" },
  quote:       { icon: "💬", label: "Daily Quote" },
  xp:          { icon: "⚡", label: "XP & Level" },
  badges:      { icon: "🎖️", label: "Badges" },
  roadmaplearn:{ icon: "🗺️", label: "Learning Roadmap" },
  challenges:  { icon: "💻", label: "Challenges" },
  deadlines:   { icon: "⏰", label: "Deadlines" },
  quickactions:{ icon: "⚡", label: "Quick Actions" },
};

export const ROLE_SECTIONS = {
  developer:    ["xp","learning","challenges","projects","activity","achievements","badges","leaderboard","jobs","saved","calendar","deadlines","quickactions","weather","quote"],
  professional: ["skills","jobs","activity","achievements","saved","analytics","calendar","notifications","quickactions"],
  creator:      ["content","revenue","activity","achievements","analytics","badges","calendar","quickactions"],
  freelancer:   ["projects","clients","activity","saved","revenue","calendar","deadlines","quickactions"],
  founder:      ["roadmap","team","activity","projects","analytics","calendar","quickactions"],
  enterprise:   ["team","training","compliance","activity","analytics","calendar","notifications"],
  instructor:   ["students","courses","gradebook","activity","analytics","calendar","quickactions"],
  recruiter:    ["pipeline","candidates","assessments","activity","analytics","calendar","quickactions"],
  admin:        ["users","moderation","revenue","activity","analytics","notifications","quickactions"],
};

// Widget definitions — id, title, icon, size, ai/realtime flags, viewAllLink
export const WIDGETS = {
  xp:           { id:"xp",           title:"XP & Level",         icon:"⚡", defaultSize:"small",  realtime:true,  aiPowered:false, viewAllLink:"/learning/achievements" },
  learning:     { id:"learning",     title:"Learning Progress",  icon:"📚", defaultSize:"medium", realtime:false, aiPowered:true,  viewAllLink:"/learning/courses" },
  challenges:   { id:"challenges",   title:"Challenges",         icon:"💻", defaultSize:"medium", realtime:false, aiPowered:true,  viewAllLink:"/learning/challenges" },
  projects:     { id:"projects",     title:"Projects",           icon:"📝", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:"/projects" },
  activity:     { id:"activity",     title:"Recent Activity",    icon:"⚡", defaultSize:"medium", realtime:true,  aiPowered:false, viewAllLink:null },
  achievements: { id:"achievements", title:"Achievements",       icon:"🏆", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:"/learning/achievements" },
  badges:       { id:"badges",       title:"Badges",             icon:"🎖️", defaultSize:"small",  realtime:false, aiPowered:false, viewAllLink:"/learning/badges" },
  leaderboard:  { id:"leaderboard",  title:"Leaderboard",        icon:"🏅", defaultSize:"medium", realtime:true,  aiPowered:false, viewAllLink:"/learning/leaderboard" },
  jobs:         { id:"jobs",         title:"Job Applications",   icon:"💼", defaultSize:"medium", realtime:false, aiPowered:true,  viewAllLink:"/jobs/applications" },
  saved:        { id:"saved",        title:"Saved Items",        icon:"🔖", defaultSize:"small",  realtime:false, aiPowered:false, viewAllLink:null },
  calendar:     { id:"calendar",     title:"Calendar",           icon:"📅", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:null },
  deadlines:    { id:"deadlines",    title:"Deadlines",          icon:"⏰", defaultSize:"small",  realtime:false, aiPowered:false, viewAllLink:null },
  quickactions: { id:"quickactions", title:"Quick Actions",      icon:"⚡", defaultSize:"small",  realtime:false, aiPowered:false, viewAllLink:null },
  weather:      { id:"weather",      title:"Weather",            icon:"🌤️", defaultSize:"small",  realtime:false, aiPowered:false, viewAllLink:null },
  quote:        { id:"quote",        title:"Daily Quote",        icon:"💬", defaultSize:"small",  realtime:false, aiPowered:true,  viewAllLink:null },
  skills:       { id:"skills",       title:"Skill Analytics",    icon:"🎯", defaultSize:"large",  realtime:false, aiPowered:true,  viewAllLink:"/learning/skills" },
  analytics:    { id:"analytics",    title:"Analytics",          icon:"📈", defaultSize:"large",  realtime:true,  aiPowered:true,  viewAllLink:null },
  revenue:      { id:"revenue",      title:"Revenue",            icon:"💰", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:"/creator/earnings" },
  content:      { id:"content",      title:"Content",            icon:"📝", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:null },
  clients:      { id:"clients",      title:"Clients",            icon:"👥", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:null },
  roadmap:      { id:"roadmap",      title:"Product Roadmap",    icon:"🗺️", defaultSize:"large",  realtime:false, aiPowered:false, viewAllLink:null },
  team:         { id:"team",         title:"Team",               icon:"👥", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:"/enterprise/teams" },
  training:     { id:"training",     title:"Training",           icon:"📚", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:null },
  compliance:   { id:"compliance",   title:"Compliance",         icon:"✅", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:"/enterprise/compliance" },
  students:     { id:"students",     title:"Students",           icon:"👨‍🎓", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:null },
  courses:      { id:"courses",      title:"Courses",            icon:"📖", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:"/learning/courses" },
  gradebook:    { id:"gradebook",    title:"Gradebook",          icon:"📋", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:null },
  pipeline:     { id:"pipeline",     title:"Hiring Pipeline",    icon:"🔄", defaultSize:"large",  realtime:true,  aiPowered:true,  viewAllLink:null },
  candidates:   { id:"candidates",   title:"Candidates",         icon:"👤", defaultSize:"medium", realtime:false, aiPowered:true,  viewAllLink:null },
  assessments:  { id:"assessments",  title:"Assessments",        icon:"📊", defaultSize:"medium", realtime:false, aiPowered:false, viewAllLink:null },
  users:        { id:"users",        title:"User Management",    icon:"👥", defaultSize:"large",  realtime:true,  aiPowered:false, viewAllLink:"/admin/users" },
  moderation:   { id:"moderation",   title:"Moderation Queue",   icon:"🛡️", defaultSize:"medium", realtime:true,  aiPowered:false, viewAllLink:null },
  notifications:{ id:"notifications",title:"Notifications",      icon:"🔔", defaultSize:"medium", realtime:true,  aiPowered:false, viewAllLink:null },
};
