global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ethiocode-backend
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /metrics

  - job_name: mongodb
    static_configs:
      - targets: ['mongodb:27017']

  - job_name: redis
    static_configs:
      - targets: ['redis:6379']
